feature: support mapping for discriminator
Redocly/ajv pull request #6
Opened 2021-10-28 14:05 UTC by slavikbez

**What issue does this pull request resolve?**

Fixes [#235](https://github.com/Redocly/openapi-cli/issues/235)

**What changes did you make?**

Implemented support for mapping in discriminator

**Note**
`no-invalid-media-type-examples` should be configured with `disallowAdditionalProperties` set to false:
```yaml
lint:
  rules:
    no-invalid-media-type-examples:
      severity: warn
      disallowAdditionalProperties: false
```
as stated [here](https://github.com/Redocly/openapi-cli/issues/230#issuecomment-735149765)

**Is there anything that requires more attention while reviewing?**

**Testing**

Tested with following examples

<details>
   <summary>Schema with references</summary>

```json
{
  "openapi": "3.0.2",
  "info": {
    "title": "API",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "//petstore.swagger.io/v2",
      "description": "Default server"
    }
  ],
  "components": {
    "schemas": {
      "Pet": {
        "type": "object",
        "properties": {
          "petType": {
            "type": "string",
            "enum": [
              "Dog",
              "Cat"
            ]
          }
        }
      },
      "Dog": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/Pet"
          },
          {
            "type": "object",
            "properties": {
              "packSize": {
                "type": "integer"
              }
            }
          }
        ]
      },
      "Cat": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/Pet"
          },
          {
            "type": "object",
            "properties": {
              "huntingSkill": {
                "type": "string"
              }
            }
          }
        ]
      },
      "House": {
        "type": "object",
        "properties": {
          "address": {
            "type": "string"
          },
          "pet": {
            "type": "object",
            "oneOf": [
              {
                "$ref": "#/components/schemas/Dog"
              },
              {
                "$ref": "#/components/schemas/Cat"
              }
            ],
            "discriminator": {
              "propertyName": "petType",
              "mapping": {
                "dog": "#/components/schemas/Dog",
                "cat": "#/components/schemas/Cat"
              }
            }
          }
        }
      }
    }
  },
  "paths": {
    "/house": {
      "post": {
        "operationId": "newHouse",
        "summary": "New house",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/House"
              },
              "examples": {
                "HouseWithDog": {
                  "value": {
                    "pet": {
                      "petType": "dog",
                      "packSize": 1
                    },
                    "address": "abc"
                  }
                },
                "HouseWithCat": {
                  "value": {
                    "pet": {
                      "petType": "cat",
                      "huntingSkill": "adventurous"
                    },
                    "address": "abc"
                  }
                }
              }
            }
          }
        },
        "responses": {

        }
      }
    }
  }
}

```
</details>

<details>
  <summary>Dereferenced schema</summary>

  ```json
   {
  "openapi": "3.0.2",
  "info": {
    "title": "API",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "//petstore.swagger.io/v2",
      "description": "Default server"
    }
  ],
  "components": {
    "schemas": {
      "Pet": {
        "type": "object",
        "properties": {
          "petType": {
            "type": "string",
            "enum": [
              "Dog",
              "Cat"
            ]
          }
        }
      },
      "Dog": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/Pet"
          },
          {
            "type": "object",
            "properties": {
              "packSize": {
                "type": "integer"
              }
            }
          }
        ]
      },
      "Cat": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/Pet"
          },
          {
            "type": "object",
            "properties": {
              "huntingSkill": {
                "type": "string"
              }
            }
          }
        ]
      },
      "House": {
        "type": "object",
        "properties": {
          "address": {
            "type": "string"
          },
          "pet": {
            "type": "object",
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "petType": {
                    "type": "string",
                    "enum": [
                      "dog"
                    ]
                  },
                  "packSize": {
                    "type": "integer"
                  }
                },
                "required": [
                  "petType"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "petType": {
                    "type": "string",
                    "enum": [
                      "cat"
                    ]
                  },
                  "huntingSkill": {
                    "type": "string"
                  }
                },
                "required": [
                  "petType"
                ]
              }
            ],
            "discriminator": {
              "propertyName": "petType",
              "mapping": {
                "dog": "#/components/schemas/Dog",
                "cat": "#/components/schemas/Cat"
              }
            }
          }
        }
      }
    }
  },
  "paths": {
    "/house": {
      "post": {
        "operationId": "newHouse",
        "summary": "New house",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/House"
              },
              "examples": {
                "HouseWithDog": {
                  "value": {
                    "pet": {
                      "petType": "dog",
                      "packSize": 1
                    },
                    "address": "abc"
                  }
                },
                "HouseWithCat": {
                  "value": {
                    "pet": {
                      "petType": "cat",
                      "huntingSkill": "adventurous"
                    },
                    "address": "abc"
                  }
                }
              }
            }
          }
        },
        "responses": {

        }
      }
    }
  }
}
  ```
</details>

2021-10-28 17:27 UTC, RomanHotsiy requested changes
Looks muuuch simpler now 😄

2021-10-28 17:27 UTC, RomanHotsiy commented on lib/vocabularies/discriminator/index.ts
> +          Object.keys(mapping).forEach(function(key) {
mapping may be undefined and it will crash with "cannot convert undefined to Object"

2021-10-28 17:27 UTC, RomanHotsiy commented on lib/vocabularies/discriminator/index.ts
> +          continue;
I would add throw here to require mapping for every $ref. Otherwise we will miss some cases.

2021-10-28 18:33 UTC, slavikbez commented on lib/vocabularies/discriminator/index.ts
> +          Object.keys(mapping).forEach(function(key) {
you're right

2021-10-29 15:01 UTC, slavikbez commented on lib/vocabularies/discriminator/index.ts
> +          continue;
I don't quite understand why we need to throw here

2021-10-29 15:29 UTC, slavikbez commented on lib/vocabularies/discriminator/index.ts
> +          continue;
never mind. We will throw an error if the given ref doesn't have corresponding entry in mapping

2021-10-29 15:55 UTC, RomanHotsiy approved these changes

2021-11-01 07:18 UTC, merged